using Test
using Bennett

include("test_parse.jl")
include("test_increment.jl")
include("test_polynomial.jl")
include("test_bitwise.jl")
include("test_compare.jl")
include("test_two_args.jl")
include("test_controlled.jl")
include("test_branch.jl")
include("test_loop.jl")
include("test_combined.jl")
include("test_int16.jl")
include("test_int32.jl")
include("test_int64.jl")
include("test_mixed_width.jl")
include("test_loop_explicit.jl")
include("test_tuple.jl")
include("test_softfloat.jl")
include("test_softfmul.jl")
include("test_softfma.jl")
include("test_softfsub.jl")
include("test_softfcmp.jl")
include("test_softfdiv.jl")
include("test_softfsqrt.jl")
include("test_softfexp.jl")
include("test_softfexp_julia.jl")
include("test_softfconv.jl")
include("test_float_circuit.jl")
include("test_float_poly.jl")
include("test_predicated_phi.jl")
include("test_extractvalue.jl")
include("test_general_call.jl")
include("test_division.jl")
include("test_ntuple_input.jl")
include("test_ancilla_reuse.jl")
include("test_dep_dag.jl")
include("test_pebbling.jl")
include("test_eager_bennett.jl")
include("test_switch.jl")
include("test_rev_memory.jl")
include("test_sat_pebbling.jl")
include("test_intrinsics.jl")
include("test_liveness.jl")
include("test_sha256.jl")
include("test_value_eager.jl")
include("test_pebbled_wire_reuse.jl")
include("test_constant_fold.jl")
include("test_var_gep.jl")
include("test_float_intrinsics.jl")
include("test_gate_count_regression.jl")
include("test_negative.jl")
include("test_soft_sitofp.jl")
include("test_sret.jl")
include("test_sha256_full.jl")
include("test_constant_wire_count.jl")
include("test_pebbled_space.jl")
include("test_wire_allocator.jl")
include("test_soft_fround.jl")
include("test_callee_bennett.jl")
include("test_cuccaro_safety.jl")
include("test_narrow.jl")
include("test_preprocessing.jl")
include("test_t0_preprocessing.jl")
include("test_ir_memory_types.jl")
include("test_store_alloca_extract.jl")
include("test_soft_mux_mem.jl")
include("test_soft_mux_mem_circuit.jl")
include("test_soft_mux_mem_guarded.jl")
include("test_lower_store_alloca.jl")
include("test_mutable_array.jl")
include("test_soft_mux_scaling.jl")
include("test_qrom.jl")
include("test_qrom_dispatch.jl")
include("test_memssa.jl")
include("test_memssa_integration.jl")
include("test_feistel.jl")
include("test_shadow_memory.jl")
include("test_universal_dispatch.jl")
include("test_memory_corpus.jl")
include("test_toffoli_depth.jl")
include("test_fast_copy.jl")
include("test_partial_products.jl")
include("test_qcla.jl")
include("test_add_dispatcher.jl")
include("test_parallel_adder_tree.jl")
include("test_mul_qcla_tree.jl")
include("test_mul_qcla_tree_paper_match.jl")
include("test_self_reversing.jl")
include("test_mul_dispatcher.jl")
include("test_softfdiv_subnormal.jl")
include("test_tabulate.jl")
# T5 — persistent map protocol + harness self-test (T5-P3a, GREEN today).
include("test_persistent_interface.jl")
# T5-P3b — Okasaki RBT persistent map (insert + lookup; delete deferred).
include("test_persistent_okasaki.jl")
# T5-P3c — Bagwell HAMT + reversible popcount (Bennett-a7zy).
include("test_persistent_hamt.jl")
# T5-P3d — Conchon-Filliâtre semi-persistent (Bennett-6thy).
include("test_persistent_cf.jl")
# T5-P4 — Hash-cons compression layers (Bennett-gv8g + Bennett-7pgw).
include("test_persistent_hashcons.jl")

# T5 corpora — multi-language RED tests (T5-P2a/b/c).  All currently RED
# via @test_throws; safe to include unconditionally.  C and Rust corpora
# self-skip if clang/rustc not on PATH.  Set BENNETT_T5_TESTS=0 to skip all.
if get(ENV, "BENNETT_T5_TESTS", "1") != "0"
    include("test_t5_corpus_julia.jl")
    include("test_t5_corpus_c.jl")
    include("test_t5_corpus_rust.jl")
end
