using Test
using Bennett
using LLVM

# T5 corpus — Rust via rustc (T5-P2c)
#
# Post-T5-P5a (2026-04-21): `extract_parsed_ir_from_ll` now exists. Rust
# fixtures use `#[no_mangle]` so the entry names (`vec_push_sum`,
# `hashmap_roundtrip`, `box_list`) appear unmangled in the emitted .ll.
# `reversible_compile(parsed)` still throws until T5-P6 lands.
#
# Bucket mapping (Bennett-Memory-T5-PRD.md §3):
#   T5 — universal fallback: unbounded dynamic memory
#   (Vec::push, HashMap insert+get, Box-based linked list)
#
# Fixture source files: test/fixtures/rust/t5_tr*.rs
# Compiled .ll output: build/t5_tr*.ll (generated by this harness)
# Rustc version: 1.95.0 (59807616e 2026-04-14)

const RUST_FIXTURES = joinpath(@__DIR__, "fixtures", "rust")
const BUILD_DIR = joinpath(@__DIR__, "..", "build")

# Locate rustc via PATH (login-shell to pick up ~/.cargo/bin)
const RUSTC_PATH = strip(read(`bash -lc "which rustc 2>/dev/null || true"`, String))

have_rustc = !isempty(RUSTC_PATH) && isfile(RUSTC_PATH)

@testset "T5 corpus — Rust via rustc (T5-P2c)" begin

    if !have_rustc
        @info "Skipping Rust T5 corpus: rustc not found on PATH (login shell)"
        # Emit one @test so the testset isn't empty
        @test_skip "rustc not available"
    else

        mkpath(BUILD_DIR)

        # ─────────────────────────────────────────────────────────────────────
        # TR1 — Vec<i8> push×3 + iter().fold() sum
        #
        # Pattern: unbounded vector (dynamic n_elems).
        # Source: test/fixtures/rust/t5_tr1_vec_push.rs
        # Reference: vec_push_sum(x) = x + (x+1) + (x+2) = 3x+3 (mod 256/i8)
        #
        # Current error (2026-04-17):
        #   UndefVarError: `extract_parsed_ir_from_ll` not defined
        # Root cause: T5-P5a (extract_parsed_ir_from_ll) is not yet implemented.
        # Once T5-P5a lands, error will shift to the lowering pipeline
        # ("dynamic n_elems not supported") until T5-P6 (:persistent_tree) lands.
        # ─────────────────────────────────────────────────────────────────────
        @testset "TR1: Vec<i8> push×3 + iter sum" begin
            rs_src = joinpath(RUST_FIXTURES, "t5_tr1_vec_push.rs")
            ll_out = joinpath(BUILD_DIR, "t5_tr1_vec_push.ll")

            # Compile rust → .ll
            run(`bash -lc "$(RUSTC_PATH) --emit=llvm-ir -C opt-level=0 --crate-type lib --edition 2021 -o $(ll_out) $(rs_src)"`)
            @test isfile(ll_out)

            # Post-T5-P5a: extraction may succeed (Rust emits very large IR
            # at -C opt-level=0, so the walker may hit unsupported opcodes
            # before producing a ParsedIR). Either way, the full pipeline
            # must throw ErrorException until T5-P6 lands.
            @test_throws Union{ErrorException, LLVM.LLVMException} begin
                parsed = Bennett.extract_parsed_ir_from_ll(
                    ll_out; entry_function="vec_push_sum")
                reversible_compile(parsed)
            end

            # POST-T5-P6 GREEN (uncomment when :persistent_tree arm lands):
            # parsed = Bennett.extract_parsed_ir_from_ll(ll_out; entry_function="vec_push_sum")
            # c = reversible_compile(parsed)
            # for x in typemin(Int8):typemax(Int8)
            #     expected = Int8(x) + Int8(x + 1) + Int8(x + 2)   # = 3x+3 (mod 256)
            #     @test simulate(c, Int8(x)) == expected
            # end
            # @test verify_reversibility(c; n_tests=3)
            # println("  TR1: ", gate_count(c))
        end

        # ─────────────────────────────────────────────────────────────────────
        # TR2 — HashMap<i8,i8> insert + get roundtrip
        #
        # Pattern: dynamic-n_elems + hashing (std::collections::HashMap).
        # Source: test/fixtures/rust/t5_tr2_hashmap.rs
        # Note: rustc 1.95.0 emits 6,113 LLVM lines for this file at opt-level=0.
        #   This is under the 10k-line fallback threshold (PRD §7.3), so the
        #   standard HashMap is used directly.  See test/fixtures/rust/README.md.
        # Reference: hashmap_roundtrip(k, v) == v  (lookup returns inserted value)
        #
        # Current error (2026-04-17):
        #   UndefVarError: `extract_parsed_ir_from_ll` not defined
        # Root cause: same as TR1 — T5-P5a not yet implemented.
        # ─────────────────────────────────────────────────────────────────────
        @testset "TR2: HashMap<i8,i8> insert + get roundtrip" begin
            rs_src = joinpath(RUST_FIXTURES, "t5_tr2_hashmap.rs")
            ll_out = joinpath(BUILD_DIR, "t5_tr2_hashmap.ll")

            # Compile rust → .ll
            run(`bash -lc "$(RUSTC_PATH) --emit=llvm-ir -C opt-level=0 --crate-type lib --edition 2021 -o $(ll_out) $(rs_src)"`)
            @test isfile(ll_out)

            # Post-T5-P5a: full pipeline throws ErrorException until T5-P6
            # lands (see TR1 note).
            @test_throws Union{ErrorException, LLVM.LLVMException} begin
                parsed = Bennett.extract_parsed_ir_from_ll(
                    ll_out; entry_function="hashmap_roundtrip")
                reversible_compile(parsed)
            end

            # POST-T5-P6 GREEN (uncomment when :persistent_tree arm lands):
            # parsed = Bennett.extract_parsed_ir_from_ll(ll_out; entry_function="hashmap_roundtrip")
            # c = reversible_compile(parsed)
            # for k in (Int8(-5), Int8(0), Int8(42), Int8(127)),
            #     v in (Int8(-1), Int8(0), Int8(7))
            #     @test simulate(c, (k, v)) == v  # lookup always returns inserted v
            # end
            # @test verify_reversibility(c; n_tests=3)
            # println("  TR2: ", gate_count(c))
        end

        # ─────────────────────────────────────────────────────────────────────
        # TR3 — Box<Node> singly-linked list (3 nodes)
        #
        # Pattern: Box heap-allocation with mutable recursive type.
        # Source: test/fixtures/rust/t5_tr3_box_list.rs
        # Reference: box_list(x) == x  (returns head node's val, which is x)
        #
        # Current error (2026-04-17):
        #   UndefVarError: `extract_parsed_ir_from_ll` not defined
        # Root cause: same as TR1 — T5-P5a not yet implemented.
        # ─────────────────────────────────────────────────────────────────────
        @testset "TR3: Box<Node> singly-linked list (3 nodes)" begin
            rs_src = joinpath(RUST_FIXTURES, "t5_tr3_box_list.rs")
            ll_out = joinpath(BUILD_DIR, "t5_tr3_box_list.ll")

            # Compile rust → .ll
            run(`bash -lc "$(RUSTC_PATH) --emit=llvm-ir -C opt-level=0 --crate-type lib --edition 2021 -o $(ll_out) $(rs_src)"`)
            @test isfile(ll_out)

            # Post-T5-P5a: full pipeline throws ErrorException until T5-P6
            # lands (see TR1 note).
            @test_throws Union{ErrorException, LLVM.LLVMException} begin
                parsed = Bennett.extract_parsed_ir_from_ll(
                    ll_out; entry_function="box_list")
                reversible_compile(parsed)
            end

            # POST-T5-P6 GREEN (uncomment when :persistent_tree arm lands):
            # parsed = Bennett.extract_parsed_ir_from_ll(ll_out; entry_function="box_list")
            # c = reversible_compile(parsed)
            # for x in typemin(Int8):typemax(Int8)
            #     @test simulate(c, Int8(x)) == x  # n.val == x (head node)
            # end
            # @test verify_reversibility(c; n_tests=3)
            # println("  TR3: ", gate_count(c))
        end

    end  # have_rustc

end
