using Test
using Bennett

# T5 corpus — C via clang (T5-P2b)
#
# Post-T5-P5a (2026-04-21): `extract_parsed_ir_from_ll` now exists and
# succeeds on each of TC1/TC2/TC3 — extraction produces a valid ParsedIR.
# `reversible_compile(parsed)` still throws until T5-P6 lands; each test
# asserts both facts.
#
# Bucket mapping (Bennett-Memory-T5-PRD.md §3):
#   T5 — universal fallback: unbounded dynamic memory
#   (malloc + dynamic-idx, realloc growing buffer, malloc-based linked list)
#
# Fixture source files: test/fixtures/c/t5_tc*.c
# Compiled .ll output: build/t5_tc*.ll (generated by this harness)
# Clang version: 18.1.3 (Ubuntu clang version 18.1.3 (1ubuntu1))

const C_FIXTURES = joinpath(@__DIR__, "fixtures", "c")
const BUILD_DIR_C = joinpath(@__DIR__, "..", "build")

# Locate clang via PATH (login-shell to pick up system paths)
const CLANG = strip(read(`bash -lc "which clang 2>/dev/null || true"`, String))

have_clang = !isempty(CLANG) && success(`bash -lc "$CLANG --version"`)

@testset "T5 corpus — C via clang (T5-P2b)" begin

    if !have_clang
        # Bennett-srsy / U103: BENNETT_CI=1 promotes the missing-clang
        # skip to a hard failure so an incomplete CI image can't quietly
        # bypass the C T5 corpus. Default (no env var) is silent skip so
        # local contributors without clang aren't blocked.
        if get(ENV, "BENNETT_CI", "0") == "1"
            error("test_t5_corpus_c: clang not found on PATH but BENNETT_CI=1; " *
                  "the multi-language T5 corpus requires the full toolchain in CI mode " *
                  "(Bennett-srsy / U103)")
        end
        @info "Skipping C T5 corpus: clang not found on PATH (login shell)"
        # Emit one @test so the testset isn't empty
        @test_skip "clang not available"
    else

        mkpath(BUILD_DIR_C)

        # ─────────────────────────────────────────────────────────────────────
        # TC1 — malloc + dynamic (runtime) array index
        #
        # Pattern: heap array with a runtime-variable index (dynamic idx).
        # Source: test/fixtures/c/t5_tc1_malloc_idx.c
        # Reference: malloc_idx_inc(x, i) == x + (i & 7)
        #
        # Current error (2026-04-17):
        #   UndefVarError: `extract_parsed_ir_from_ll` not defined
        # Root cause: T5-P5a (extract_parsed_ir_from_ll) is not yet implemented.
        # Once T5-P5a lands, error will shift to the lowering pipeline
        # ("dynamic n_elems not supported") until T5-P6 (:persistent_tree) lands.
        # ─────────────────────────────────────────────────────────────────────
        @testset "TC1: malloc + dynamic-idx array (malloc_idx_inc)" begin
            c_src = joinpath(C_FIXTURES, "t5_tc1_malloc_idx.c")
            ll_out = joinpath(BUILD_DIR_C, "t5_tc1_malloc_idx.ll")

            # Compile C → .ll
            run(`bash -lc "$CLANG -O0 -emit-llvm -S -o $ll_out $c_src"`)
            @test isfile(ll_out)

            # Post-Bennett-5oyt / U15: extraction now loud-errors on the
            # unregistered `malloc` callee (pre-U15 silent-dropped it and
            # the subsequent `reversible_compile` was what threw). Same
            # bottom-line assertion — the pipeline cannot handle malloc
            # until T5-P6 — but the failure surfaces earlier.
            @test_throws ErrorException Bennett.extract_parsed_ir_from_ll(
                ll_out; entry_function="malloc_idx_inc")

            # POST-T5-P6 GREEN (uncomment when :persistent_tree arm lands):
            # parsed = Bennett.extract_parsed_ir_from_ll(
            #     ll_out; entry_function="malloc_idx_inc")
            # c = reversible_compile(parsed)
            # for x in typemin(Int8):typemax(Int8), i in typemin(Int8):typemax(Int8)
            #     expected = x + Int8(i & 7)    # v[i & 7] = x + (i & 7)
            #     @test simulate(c, (Int8(x), Int8(i))) == expected
            # end
            # @test verify_reversibility(c; n_tests=3)
            # println("  TC1: ", gate_count(c))
        end

        # ─────────────────────────────────────────────────────────────────────
        # TC2 — growing buffer via realloc
        #
        # Pattern: malloc + realloc (resize semantics).
        # Source: test/fixtures/c/t5_tc2_realloc.c
        # Reference: realloc_buf(x) == x + (x+1) + (x+2) + (x+3) = 4x+6 (mod 256)
        #
        # Current error (2026-04-17):
        #   UndefVarError: `extract_parsed_ir_from_ll` not defined
        # Root cause: same as TC1 — T5-P5a not yet implemented.
        # ─────────────────────────────────────────────────────────────────────
        @testset "TC2: realloc growing buffer (realloc_buf)" begin
            c_src = joinpath(C_FIXTURES, "t5_tc2_realloc.c")
            ll_out = joinpath(BUILD_DIR_C, "t5_tc2_realloc.ll")

            # Compile C → .ll
            run(`bash -lc "$CLANG -O0 -emit-llvm -S -o $ll_out $c_src"`)
            @test isfile(ll_out)

            # Post-Bennett-5oyt / U15: extraction loud-errors on the
            # unregistered malloc/realloc callees.
            @test_throws ErrorException Bennett.extract_parsed_ir_from_ll(
                ll_out; entry_function="realloc_buf")

            # POST-T5-P6 GREEN (uncomment when :persistent_tree arm lands):
            # c = reversible_compile(parsed)
            # for x in typemin(Int8):typemax(Int8)
            #     expected = x + Int8(x+1) + Int8(x+2) + Int8(x+3)  # 4x+6 mod 256
            #     @test simulate(c, Int8(x)) == expected
            # end
            # @test verify_reversibility(c; n_tests=3)
            # println("  TC2: ", gate_count(c))
        end

        # ─────────────────────────────────────────────────────────────────────
        # TC3 — malloc-based singly-linked list (3 nodes)
        #
        # Pattern: malloc + pointer-chained recursive type (mutable linked list).
        # Source: test/fixtures/c/t5_tc3_malloc_list.c
        # Reference: malloc_list(x) == x + (x+1) + (x+2) = 3x+3 (mod 256)
        #
        # Current error (2026-04-17):
        #   UndefVarError: `extract_parsed_ir_from_ll` not defined
        # Root cause: same as TC1 — T5-P5a not yet implemented.
        # ─────────────────────────────────────────────────────────────────────
        @testset "TC3: malloc-based singly-linked list (malloc_list)" begin
            c_src = joinpath(C_FIXTURES, "t5_tc3_malloc_list.c")
            ll_out = joinpath(BUILD_DIR_C, "t5_tc3_malloc_list.ll")

            # Compile C → .ll
            run(`bash -lc "$CLANG -O0 -emit-llvm -S -o $ll_out $c_src"`)
            @test isfile(ll_out)

            # Post-Bennett-5oyt / U15: extraction loud-errors on the
            # unregistered malloc callee.
            @test_throws ErrorException Bennett.extract_parsed_ir_from_ll(
                ll_out; entry_function="malloc_list")

            # POST-T5-P6 GREEN (uncomment when :persistent_tree arm lands):
            # c = reversible_compile(parsed)
            # for x in typemin(Int8):typemax(Int8)
            #     expected = x + Int8(x+1) + Int8(x+2)  # 3x+3 mod 256
            #     @test simulate(c, Int8(x)) == expected
            # end
            # @test verify_reversibility(c; n_tests=3)
            # println("  TC3: ", gate_count(c))
        end

    end  # have_clang

end
