# scripts/gen_heap_fixtures.jl — Bennett-2mj3.
#
# Regenerate the heap-memory .ll fixtures used by test_t5_corpus_julia.jl,
# test_gps7_heap_m1.jl, test_5ikt_heap_m3.jl and test_bd5f_heap_m4.jl.
#
# WHY this script exists: `Pkg.test()` runs Julia with `--check-bounds=yes`,
# which forces every `@boundscheck` ON. Under that mode the heap-memory
# functions' IR carries an extra `@ijl_bounds_error_int` call that the
# heap recogniser (correctly, FAIL-LOUD) rejects — so the happy-path tests
# cannot `code_llvm` their own subjects in-suite, and the reject tests
# reject for the wrong (bounds-error) reason. The fix is to drive those
# tests off PRE-CAPTURED .ll fixtures dumped under DEFAULT check-bounds,
# which is the IR shape the recogniser was designed for.
#
# RUN THIS UNDER DEFAULT CHECK-BOUNDS — i.e. plain:
#     julia --project scripts/gen_heap_fixtures.jl
# NOT `--check-bounds=yes`. The script asserts the captured IR is free of
# `@ijl_bounds_error` so a wrong invocation fails loud.
#
# Fixtures are dumped with optimize=true, dump_module=true — the exact
# settings extract_parsed_ir uses for mem=:heap.

using InteractiveUtils: code_llvm

const FIX = joinpath(@__DIR__, "..", "test", "fixtures")

# --- happy-path heap functions (must compile under mem=:heap) -------------
f1(x::Int8) = let v = Int8[]; push!(v, x); v[1] end

f_tj1(x::Int8) = let v = Int8[]
    push!(v, x)
    push!(v, x + Int8(1))
    push!(v, x + Int8(2))
    reduce(+, v)
end

f_tj1_2push(x::Int8) = let v = Int8[]
    push!(v, x)
    push!(v, x + Int8(1))
    reduce(+, v)
end

# --- reject-case heap functions -------------------------------------------
# M3/M4 runtime-count push! in a loop — rejects on the M1 back-edge guard.
floop(x::Int8) = let v = Int8[]
    for k in Int8(1):x
        push!(v, k)
    end
    reduce(+, v)
end

# push! inside a runtime if — rejects via the M2 bounds-diamond collapse.
fif(x::Int8) = let v = Int8[]
    push!(v, x)
    if x > Int8(0)
        push!(v, x + Int8(1))
    end
    reduce(+, v)
end

# escaping vector whose reduce loops — rejects on the M1 back-edge guard.
@noinline _m3_sink(v::Vector{Int8}) = length(v)
_m3_escape(x::Int8) = let v = Int8[]
    push!(v, x)
    push!(v, x + Int8(1))
    Int8(_m3_sink(v)) + reduce(+, v)
end

function dump_fixture(name::AbstractString, f, argtypes::Type{<:Tuple})
    ir = sprint(io -> code_llvm(io, f, argtypes;
                                debuginfo=:none, optimize=true, dump_module=true))
    if occursin("ijl_bounds_error", ir)
        error("gen_heap_fixtures: $name IR contains an `ijl_bounds_error` " *
              "call — this script MUST be run under DEFAULT check-bounds " *
              "(plain `julia --project`, NOT `--check-bounds=yes`).")
    end
    path = joinpath(FIX, name)
    open(path, "w") do io
        write(io, "; AUTO-GENERATED by scripts/gen_heap_fixtures.jl (Bennett-2mj3).\n")
        write(io, "; Source: $name — captured from `code_llvm(...; optimize=true,\n")
        write(io, ";   dump_module=true)` under DEFAULT check-bounds. Regenerate with\n")
        write(io, ";   `julia --project scripts/gen_heap_fixtures.jl` (NOT --check-bounds=yes).\n")
        write(io, ir)
    end
    println("wrote $path  ($(count(==('\n'), ir)) IR lines)")
end

dump_fixture("heap_m1_f1.ll",          f1,          Tuple{Int8})
dump_fixture("heap_m3_tj1.ll",         f_tj1,       Tuple{Int8})
dump_fixture("heap_m3_tj1_2push.ll",   f_tj1_2push, Tuple{Int8})
dump_fixture("heap_reject_floop.ll",   floop,       Tuple{Int8})
dump_fixture("heap_reject_fif.ll",     fif,         Tuple{Int8})
dump_fixture("heap_reject_escape.ll",  _m3_escape,  Tuple{Int8})
println("done.")
