; AUTO-GENERATED by scripts/gen_heap_fixtures.jl (Bennett-2mj3).
; Source: heap_reject_floop.ll — captured from `code_llvm(...; optimize=true,
;   dump_module=true)` under DEFAULT check-bounds. Regenerate with
;   `julia --project scripts/gen_heap_fixtures.jl` (NOT --check-bounds=yes).
; ModuleID = 'floop'
source_filename = "floop"
target datalayout = "e-m:e-p270:32:32-p271:32:32-p272:64:64-i64:64-i128:128-f80:128-n8:16:32:64-S128"
target triple = "x86_64-unknown-linux-gnu"

@jl_boxed_int8_cache = external constant [256 x ptr]

@"+Core.Array#319.jit" = private alias ptr, inttoptr (i64 139761035024784 to ptr)
@"jl_global#318.jit" = private alias ptr, inttoptr (i64 139761038565856 to ptr)

; Function Signature: floop(Int8)
define i8 @julia_floop_316(i8 signext %"x::Int8") #0 {
top:
  %gcframe1 = alloca [7 x ptr], align 16
  call void @llvm.memset.p0.i64(ptr align 16 %gcframe1, i8 0, i64 56, i1 true)
  %0 = getelementptr inbounds ptr, ptr %gcframe1, i64 5
  %1 = getelementptr inbounds ptr, ptr %gcframe1, i64 2
  %"new::#_growend!##0#_growend!##1" = alloca [9 x i64], align 8
  %sret_box = alloca [2 x i64], align 8
  %thread_ptr = call ptr asm "movq %fs:0, $0", "=r"() #13
  %tls_ppgcstack = getelementptr inbounds i8, ptr %thread_ptr, i64 -8
  %tls_pgcstack = load ptr, ptr %tls_ppgcstack, align 8
  store i64 20, ptr %gcframe1, align 8
  %frame.prev = getelementptr inbounds ptr, ptr %gcframe1, i64 1
  %task.gcstack = load ptr, ptr %tls_pgcstack, align 8
  store ptr %task.gcstack, ptr %frame.prev, align 8
  store ptr %gcframe1, ptr %tls_pgcstack, align 8
  %memory_data = load ptr, ptr getelementptr inbounds (ptr, ptr @"jl_global#318.jit", i64 1), align 8
  %ptls_field = getelementptr inbounds i8, ptr %tls_pgcstack, i64 16
  %ptls_load = load ptr, ptr %ptls_field, align 8
  %"new::Array" = call noalias nonnull align 8 dereferenceable(32) ptr @ijl_gc_small_alloc(ptr %ptls_load, i32 408, i32 32, i64 139761035024784) #10
  %"new::Array.tag_addr" = getelementptr inbounds i64, ptr %"new::Array", i64 -1
  store atomic i64 139761035024784, ptr %"new::Array.tag_addr" unordered, align 8
  %2 = getelementptr inbounds i8, ptr %"new::Array", i64 8
  store ptr %memory_data, ptr %"new::Array", align 8
  store ptr @"jl_global#318.jit", ptr %2, align 8
  %"new::Array.size_ptr" = getelementptr inbounds i8, ptr %"new::Array", i64 16
  store i64 0, ptr %"new::Array.size_ptr", align 8
  %".x::Int8" = call i8 @llvm.smax.i8(i8 %"x::Int8", i8 0)
  %3 = icmp slt i8 %"x::Int8", 1
  br i1 %3, label %L158, label %L20.preheader

L20.preheader:                                    ; preds = %top
  %4 = getelementptr inbounds i8, ptr %"new::#_growend!##0#_growend!##1", i64 8
  %5 = getelementptr inbounds i8, ptr %"new::#_growend!##0#_growend!##1", i64 16
  %6 = getelementptr inbounds i8, ptr %"new::#_growend!##0#_growend!##1", i64 24
  %7 = getelementptr inbounds i8, ptr %"new::#_growend!##0#_growend!##1", i64 32
  %8 = getelementptr inbounds i8, ptr %"new::#_growend!##0#_growend!##1", i64 40
  %9 = getelementptr inbounds i8, ptr %"new::#_growend!##0#_growend!##1", i64 56
  %10 = getelementptr inbounds i8, ptr %"new::#_growend!##0#_growend!##1", i64 64
  %11 = getelementptr inbounds ptr, ptr %gcframe1, i64 3
  %12 = getelementptr inbounds ptr, ptr %gcframe1, i64 4
  br label %L20

L20:                                              ; preds = %L36, %L20.preheader
  %memoryref_mem97 = phi ptr [ %memoryref_mem, %L36 ], [ @"jl_global#318.jit", %L20.preheader ]
  %memoryref_data95 = phi ptr [ %memoryref_data, %L36 ], [ %memory_data, %L20.preheader ]
  %"new::Array.size.0.copyload" = phi i64 [ %13, %L36 ], [ 0, %L20.preheader ]
  %value_phi4 = phi i8 [ %19, %L36 ], [ 1, %L20.preheader ]
  %13 = add i64 %"new::Array.size.0.copyload", 1
  %memory_data_ptr7 = getelementptr inbounds { i64, ptr }, ptr %memoryref_mem97, i64 0, i32 1
  %memory_data8 = load ptr, ptr %memory_data_ptr7, align 8
  %14 = ptrtoint ptr %memory_data8 to i64
  %15 = ptrtoint ptr %memoryref_data95 to i64
  %memoryref_offset = sub i64 %15, %14
  %16 = add i64 %memoryref_offset, 1
  %17 = add i64 %16, %"new::Array.size.0.copyload"
  %.unbox = load i64, ptr %memoryref_mem97, align 8
  %.not = icmp slt i64 %.unbox, %17
  br i1 %.not, label %L34, label %L36

L34:                                              ; preds = %L20
  store i64 %17, ptr %4, align 8
  store i64 %16, ptr %5, align 8
  store i64 %13, ptr %6, align 8
  store i64 %"new::Array.size.0.copyload", ptr %7, align 8
  store i64 %.unbox, ptr %8, align 8
  store ptr %memoryref_data95, ptr %9, align 8
  store i64 -1, ptr %10, align 8
  store ptr %"new::Array", ptr %1, align 8
  store ptr %memoryref_mem97, ptr %11, align 8
  store ptr %memoryref_mem97, ptr %12, align 8
  %gc_slot_addr_4 = getelementptr inbounds ptr, ptr %gcframe1, i64 6
  store ptr %"new::Array", ptr %gc_slot_addr_4, align 8
  call void @"j_#_growend!##0_320"(ptr noalias nocapture noundef nonnull sret({ ptr, ptr }) %sret_box, ptr noalias nocapture noundef nonnull %0, ptr nocapture nonnull readonly %"new::#_growend!##0#_growend!##1", ptr nocapture nonnull readonly %1)
  %memoryref_data.pre = load ptr, ptr %"new::Array", align 8
  %memoryref_mem.pre = load ptr, ptr %2, align 8
  br label %L36

L36:                                              ; preds = %L34, %L20
  %memoryref_mem = phi ptr [ %memoryref_mem.pre, %L34 ], [ %memoryref_mem97, %L20 ]
  %memoryref_data = phi ptr [ %memoryref_data.pre, %L34 ], [ %memoryref_data95, %L20 ]
  store i64 %13, ptr %"new::Array.size_ptr", align 8
  %18 = getelementptr i8, ptr %memoryref_data, i64 %13
  %memoryref_data15 = getelementptr i8, ptr %18, i64 -1
  store i8 %value_phi4, ptr %memoryref_data15, align 1
  %.not87.not = icmp eq i8 %value_phi4, %".x::Int8"
  %19 = add nuw i8 %value_phi4, 1
  br i1 %.not87.not, label %L58, label %L20

L58:                                              ; preds = %L36
  switch i64 %"new::Array.size.0.copyload", label %L85 [
    i64 -1, label %L158
    i64 0, label %L80
  ]

L80:                                              ; preds = %L58
  %20 = load i8, ptr %memoryref_data, align 1
  br label %L158

L85:                                              ; preds = %L58
  %21 = icmp sgt i64 %13, 15
  br i1 %21, label %L150, label %L101

L101:                                             ; preds = %L85
  %22 = load i8, ptr %memoryref_data, align 1
  %memoryref_data56 = getelementptr inbounds i8, ptr %memoryref_data, i64 1
  %23 = load i8, ptr %memoryref_data56, align 1
  %24 = add i8 %23, %22
  %.not9091 = icmp sgt i64 %13, 2
  br i1 %.not9091, label %iter.check, label %L158

iter.check:                                       ; preds = %L101
  %25 = add nsw i8 %".x::Int8", -1
  %26 = zext i8 %25 to i64
  %27 = add nsw i64 %26, -1
  %min.iters.check = icmp ult i64 %27, 16
  br i1 %min.iters.check, label %vec.epilog.scalar.ph, label %vector.main.loop.iter.check

vector.main.loop.iter.check:                      ; preds = %iter.check
  %min.iters.check107 = icmp ult i64 %27, 128
  br i1 %min.iters.check107, label %vec.epilog.ph, label %vector.ph

vector.ph:                                        ; preds = %vector.main.loop.iter.check
  %n.vec = and i64 %27, -128
  %28 = insertelement <32 x i8> <i8 poison, i8 0, i8 0, i8 0, i8 0, i8 0, i8 0, i8 0, i8 0, i8 0, i8 0, i8 0, i8 0, i8 0, i8 0, i8 0, i8 0, i8 0, i8 0, i8 0, i8 0, i8 0, i8 0, i8 0, i8 0, i8 0, i8 0, i8 0, i8 0, i8 0, i8 0, i8 0>, i8 %24, i64 0
  br label %vector.body

vector.body:                                      ; preds = %vector.body, %vector.ph
  %index = phi i64 [ 0, %vector.ph ], [ %index.next, %vector.body ]
  %vec.phi = phi <32 x i8> [ %28, %vector.ph ], [ %33, %vector.body ]
  %vec.phi108 = phi <32 x i8> [ zeroinitializer, %vector.ph ], [ %34, %vector.body ]
  %vec.phi109 = phi <32 x i8> [ zeroinitializer, %vector.ph ], [ %35, %vector.body ]
  %vec.phi110 = phi <32 x i8> [ zeroinitializer, %vector.ph ], [ %36, %vector.body ]
  %offset.idx = or disjoint i64 %index, 2
  %29 = getelementptr inbounds i8, ptr %memoryref_data, i64 %offset.idx
  %30 = getelementptr inbounds i8, ptr %29, i64 32
  %31 = getelementptr inbounds i8, ptr %29, i64 64
  %32 = getelementptr inbounds i8, ptr %29, i64 96
  %wide.load = load <32 x i8>, ptr %29, align 1
  %wide.load111 = load <32 x i8>, ptr %30, align 1
  %wide.load112 = load <32 x i8>, ptr %31, align 1
  %wide.load113 = load <32 x i8>, ptr %32, align 1
  %33 = add <32 x i8> %wide.load, %vec.phi
  %34 = add <32 x i8> %wide.load111, %vec.phi108
  %35 = add <32 x i8> %wide.load112, %vec.phi109
  %36 = add <32 x i8> %wide.load113, %vec.phi110
  %index.next = add nuw i64 %index, 128
  %37 = icmp eq i64 %index.next, %n.vec
  br i1 %37, label %middle.block, label %vector.body

middle.block:                                     ; preds = %vector.body
  %bin.rdx = add <32 x i8> %34, %33
  %bin.rdx114 = add <32 x i8> %35, %bin.rdx
  %bin.rdx115 = add <32 x i8> %36, %bin.rdx114
  %38 = call i8 @llvm.vector.reduce.add.v32i8(<32 x i8> %bin.rdx115)
  %cmp.n = icmp eq i64 %27, %n.vec
  br i1 %cmp.n, label %L158, label %vec.epilog.iter.check

vec.epilog.iter.check:                            ; preds = %middle.block
  %ind.end118 = or disjoint i64 %n.vec, 2
  %n.vec.remaining = and i64 %27, 112
  %min.epilog.iters.check = icmp eq i64 %n.vec.remaining, 0
  br i1 %min.epilog.iters.check, label %vec.epilog.scalar.ph, label %vec.epilog.ph

vec.epilog.ph:                                    ; preds = %vec.epilog.iter.check, %vector.main.loop.iter.check
  %bc.merge.rdx = phi i8 [ %24, %vector.main.loop.iter.check ], [ %38, %vec.epilog.iter.check ]
  %vec.epilog.resume.val = phi i64 [ 0, %vector.main.loop.iter.check ], [ %n.vec, %vec.epilog.iter.check ]
  %n.vec117 = and i64 %27, -16
  %ind.end = or disjoint i64 %n.vec117, 2
  %39 = insertelement <16 x i8> <i8 poison, i8 0, i8 0, i8 0, i8 0, i8 0, i8 0, i8 0, i8 0, i8 0, i8 0, i8 0, i8 0, i8 0, i8 0, i8 0>, i8 %bc.merge.rdx, i64 0
  br label %vec.epilog.vector.body

vec.epilog.vector.body:                           ; preds = %vec.epilog.vector.body, %vec.epilog.ph
  %index120 = phi i64 [ %vec.epilog.resume.val, %vec.epilog.ph ], [ %index.next124, %vec.epilog.vector.body ]
  %vec.phi121 = phi <16 x i8> [ %39, %vec.epilog.ph ], [ %41, %vec.epilog.vector.body ]
  %offset.idx122 = or disjoint i64 %index120, 2
  %40 = getelementptr inbounds i8, ptr %memoryref_data, i64 %offset.idx122
  %wide.load123 = load <16 x i8>, ptr %40, align 1
  %41 = add <16 x i8> %wide.load123, %vec.phi121
  %index.next124 = add nuw i64 %index120, 16
  %42 = icmp eq i64 %index.next124, %n.vec117
  br i1 %42, label %vec.epilog.middle.block, label %vec.epilog.vector.body

vec.epilog.middle.block:                          ; preds = %vec.epilog.vector.body
  %43 = call i8 @llvm.vector.reduce.add.v16i8(<16 x i8> %41)
  %cmp.n119 = icmp eq i64 %27, %n.vec117
  br i1 %cmp.n119, label %L158, label %vec.epilog.scalar.ph

vec.epilog.scalar.ph:                             ; preds = %vec.epilog.middle.block, %vec.epilog.iter.check, %iter.check
  %bc.resume.val = phi i64 [ %ind.end, %vec.epilog.middle.block ], [ %ind.end118, %vec.epilog.iter.check ], [ 2, %iter.check ]
  %bc.merge.rdx125 = phi i8 [ %43, %vec.epilog.middle.block ], [ %38, %vec.epilog.iter.check ], [ %24, %iter.check ]
  br label %L128

L128:                                             ; preds = %L128, %vec.epilog.scalar.ph
  %value_phi5893 = phi i64 [ %44, %L128 ], [ %bc.resume.val, %vec.epilog.scalar.ph ]
  %value_phi5792 = phi i8 [ %46, %L128 ], [ %bc.merge.rdx125, %vec.epilog.scalar.ph ]
  %44 = add nuw nsw i64 %value_phi5893, 1
  %memoryref_data72 = getelementptr inbounds i8, ptr %memoryref_data, i64 %value_phi5893
  %45 = load i8, ptr %memoryref_data72, align 1
  %46 = add i8 %45, %value_phi5792
  %exitcond.not = icmp eq i64 %value_phi5893, %"new::Array.size.0.copyload"
  br i1 %exitcond.not, label %L158, label %L128

L150:                                             ; preds = %L85
  %gc_slot_addr_4132 = getelementptr inbounds ptr, ptr %gcframe1, i64 6
  store ptr %"new::Array", ptr %gc_slot_addr_4132, align 8
  %47 = call i8 @j_mapreduce_impl_322(ptr nonnull %"new::Array", i64 signext 1, i64 signext %13, i64 signext 1024)
  br label %L158

L158:                                             ; preds = %L150, %L128, %vec.epilog.middle.block, %middle.block, %L101, %L80, %L58, %top
  %value_phi21 = phi i8 [ %20, %L80 ], [ %47, %L150 ], [ 0, %L58 ], [ %24, %L101 ], [ 0, %top ], [ %38, %middle.block ], [ %43, %vec.epilog.middle.block ], [ %46, %L128 ]
  %frame.prev138 = load ptr, ptr %frame.prev, align 8
  store ptr %frame.prev138, ptr %tls_pgcstack, align 8
  ret i8 %value_phi21
}

; Function Attrs: noinline optnone
define nonnull ptr @jfptr_floop_317(ptr %"function::Core.Function", ptr noalias nocapture noundef readonly %"args::Any[]", i32 %"nargs::UInt32") #1 {
top:
  %0 = getelementptr inbounds i8, ptr %"args::Any[]", i32 0
  %1 = load ptr, ptr %0, align 8
  %.unbox = load i8, ptr %1, align 1
  %2 = call i8 @julia_floop_316(i8 signext %.unbox)
  %3 = zext i8 %2 to i32
  %4 = getelementptr inbounds [256 x ptr], ptr @jl_boxed_int8_cache, i32 0, i32 %3
  %5 = load ptr, ptr %4, align 8
  ret ptr %5
}

; Function Attrs: mustprogress nocallback nofree nosync nounwind speculatable willreturn memory(none)
declare void @llvm.dbg.value(metadata, metadata, metadata) #2

; Function Attrs: mustprogress nounwind willreturn allockind("alloc") allocsize(1) memory(argmem: read, inaccessiblemem: readwrite)
declare noalias nonnull ptr @julia.gc_alloc_obj(ptr, i64, ptr) #3

; Function Signature: (::Base.var"#_growend!##0#_growend!##1"{Array{Int8, 1}, Int64, Int64, Int64, Int64, Int64, Memory{Int8}, GenericMemoryRef{:not_atomic, Int8, Core.AddrSpace{Core}(0x00)}})()
declare void @"j_#_growend!##0_320"(ptr noalias nocapture noundef sret({ ptr, ptr }), ptr noalias nocapture noundef, ptr nocapture readonly, ptr nocapture readonly) #4

; Function Attrs: mustprogress nocallback nofree nounwind willreturn memory(argmem: write)
declare void @llvm.memset.p0.i64(ptr nocapture writeonly, i8, i64, i1 immarg) #5

; Function Attrs: mustprogress nofree norecurse nosync nounwind speculatable willreturn memory(none)
declare noundef nonnull ptr @julia.gc_loaded(ptr nocapture noundef nonnull readnone, ptr noundef nonnull readnone) #6

; Function Signature: mapreduce_impl(typeof(Base.identity), typeof(Base.:(+)), Array{Int8, 1}, Int64, Int64, Int64)
declare i8 @j_mapreduce_impl_322(ptr, i64 signext, i64 signext, i64 signext) #7

; Function Attrs: nocallback nofree nosync nounwind speculatable willreturn memory(none)
declare i8 @llvm.smax.i8(i8, i8) #8

; Function Attrs: nocallback nofree nosync nounwind willreturn memory(argmem: readwrite)
declare void @llvm.lifetime.start.p0(i64 immarg, ptr nocapture) #9

; Function Attrs: nocallback nofree nosync nounwind willreturn memory(argmem: readwrite)
declare void @llvm.lifetime.end.p0(i64 immarg, ptr nocapture) #9

; Function Attrs: nocallback nofree nosync nounwind speculatable willreturn memory(none)
declare i8 @llvm.vector.reduce.add.v32i8(<32 x i8>) #8

; Function Attrs: nocallback nofree nosync nounwind speculatable willreturn memory(none)
declare i8 @llvm.vector.reduce.add.v16i8(<16 x i8>) #8

; Function Attrs: nounwind willreturn allockind("alloc") allocsize(2) memory(argmem: read, inaccessiblemem: readwrite)
declare noalias nonnull ptr @ijl_gc_small_alloc(ptr, i32, i32, i64) #10

declare noalias nonnull ptr @julia.new_gc_frame(i32)

declare void @julia.push_gc_frame(ptr, i32)

declare ptr @julia.get_gc_frame_slot(ptr, i32)

declare void @julia.pop_gc_frame(ptr)

; Function Attrs: nounwind willreturn allockind("alloc") allocsize(1) memory(argmem: read, inaccessiblemem: readwrite)
declare noalias nonnull ptr @julia.gc_alloc_bytes(ptr, i64, i64) #11

; Function Attrs: memory(argmem: readwrite, inaccessiblemem: readwrite)
declare void @ijl_gc_queue_root(ptr) #12

; Function Attrs: nounwind willreturn allockind("alloc") allocsize(1) memory(argmem: read, inaccessiblemem: readwrite)
declare noalias nonnull ptr @ijl_gc_big_alloc(ptr, i64, i64) #11

; Function Attrs: nounwind willreturn allockind("alloc") allocsize(1) memory(argmem: read, inaccessiblemem: readwrite)
declare noalias nonnull ptr @ijl_gc_alloc_typed(ptr, i64, i64) #11

attributes #0 = { "frame-pointer"="all" "julia.fsig"="floop(Int8)" "probe-stack"="inline-asm" }
attributes #1 = { noinline optnone "frame-pointer"="all" "probe-stack"="inline-asm" }
attributes #2 = { mustprogress nocallback nofree nosync nounwind speculatable willreturn memory(none) }
attributes #3 = { mustprogress nounwind willreturn allockind("alloc") allocsize(1) memory(argmem: read, inaccessiblemem: readwrite) }
attributes #4 = { "frame-pointer"="all" "julia.fsig"="(::Base.var\22#_growend!##0#_growend!##1\22{Array{Int8, 1}, Int64, Int64, Int64, Int64, Int64, Memory{Int8}, GenericMemoryRef{:not_atomic, Int8, Core.AddrSpace{Core}(0x00)}})()" "probe-stack"="inline-asm" }
attributes #5 = { mustprogress nocallback nofree nounwind willreturn memory(argmem: write) }
attributes #6 = { mustprogress nofree norecurse nosync nounwind speculatable willreturn memory(none) }
attributes #7 = { "frame-pointer"="all" "julia.fsig"="mapreduce_impl(typeof(Base.identity), typeof(Base.:(+)), Array{Int8, 1}, Int64, Int64, Int64)" "probe-stack"="inline-asm" }
attributes #8 = { nocallback nofree nosync nounwind speculatable willreturn memory(none) }
attributes #9 = { nocallback nofree nosync nounwind willreturn memory(argmem: readwrite) }
attributes #10 = { nounwind willreturn allockind("alloc") allocsize(2) memory(argmem: read, inaccessiblemem: readwrite) }
attributes #11 = { nounwind willreturn allockind("alloc") allocsize(1) memory(argmem: read, inaccessiblemem: readwrite) }
attributes #12 = { memory(argmem: readwrite, inaccessiblemem: readwrite) }
attributes #13 = { nounwind }

!llvm.module.flags = !{!0, !1}

!0 = !{i32 2, !"Dwarf Version", i32 4}
!1 = !{i32 2, !"Debug Info Version", i32 3}
