; AUTO-GENERATED by scripts/gen_heap_fixtures.jl (Bennett-2mj3).
; Source: heap_m3_tj1.ll — captured from `code_llvm(...; optimize=true,
;   dump_module=true)` under DEFAULT check-bounds. Regenerate with
;   `julia --project scripts/gen_heap_fixtures.jl` (NOT --check-bounds=yes).
; ModuleID = 'f_tj1'
source_filename = "f_tj1"
target datalayout = "e-m:e-p270:32:32-p271:32:32-p272:64:64-i64:64-i128:128-f80:128-n8:16:32:64-S128"
target triple = "x86_64-unknown-linux-gnu"

@jl_boxed_int8_cache = external constant [256 x ptr]

@"+Core.Array#265.jit" = private alias ptr, inttoptr (i64 139761035024784 to ptr)
@"jl_global#264.jit" = private alias ptr, inttoptr (i64 139761038565856 to ptr)

; Function Signature: f_tj1(Int8)
define i8 @julia_f_tj1_262(i8 signext %"x::Int8") #0 {
top:
  %gcframe1 = alloca [15 x ptr], align 16
  call void @llvm.memset.p0.i64(ptr align 16 %gcframe1, i8 0, i64 120, i1 true)
  %0 = getelementptr inbounds ptr, ptr %gcframe1, i64 13
  %1 = getelementptr inbounds ptr, ptr %gcframe1, i64 8
  %2 = getelementptr inbounds ptr, ptr %gcframe1, i64 5
  %3 = getelementptr inbounds ptr, ptr %gcframe1, i64 2
  %"new::#_growend!##0#_growend!##1" = alloca [9 x i64], align 8
  %sret_box = alloca [2 x i64], align 8
  %"new::#_growend!##0#_growend!##119" = alloca [9 x i64], align 8
  %sret_box20 = alloca [2 x i64], align 8
  %"new::#_growend!##0#_growend!##143" = alloca [9 x i64], align 8
  %sret_box44 = alloca [2 x i64], align 8
  %thread_ptr = call ptr asm "movq %fs:0, $0", "=r"() #12
  %tls_ppgcstack = getelementptr inbounds i8, ptr %thread_ptr, i64 -8
  %tls_pgcstack = load ptr, ptr %tls_ppgcstack, align 8
  store i64 52, ptr %gcframe1, align 8
  %frame.prev = getelementptr inbounds ptr, ptr %gcframe1, i64 1
  %task.gcstack = load ptr, ptr %tls_pgcstack, align 8
  store ptr %task.gcstack, ptr %frame.prev, align 8
  store ptr %gcframe1, ptr %tls_pgcstack, align 8
  %memory_data = load ptr, ptr getelementptr inbounds (ptr, ptr @"jl_global#264.jit", i64 1), align 8
  %ptls_field = getelementptr inbounds i8, ptr %tls_pgcstack, i64 16
  %ptls_load = load ptr, ptr %ptls_field, align 8
  %"new::Array" = call noalias nonnull align 8 dereferenceable(32) ptr @ijl_gc_small_alloc(ptr %ptls_load, i32 408, i32 32, i64 139761035024784) #9
  %"new::Array.tag_addr" = getelementptr inbounds i64, ptr %"new::Array", i64 -1
  store atomic i64 139761035024784, ptr %"new::Array.tag_addr" unordered, align 8
  %4 = getelementptr inbounds i8, ptr %"new::Array", i64 8
  store ptr %memory_data, ptr %"new::Array", align 8
  store ptr @"jl_global#264.jit", ptr %4, align 8
  %"new::Array.size_ptr" = getelementptr inbounds i8, ptr %"new::Array", i64 16
  store i64 0, ptr %"new::Array.size_ptr", align 8
  %memory_data3 = load ptr, ptr getelementptr inbounds (ptr, ptr @"jl_global#264.jit", i64 1), align 8
  %5 = ptrtoint ptr %memory_data3 to i64
  %6 = ptrtoint ptr %memory_data to i64
  %memoryref_offset = sub i64 %6, %5
  %7 = add i64 %memoryref_offset, 1
  %.unbox = load i64, ptr @"jl_global#264.jit", align 8
  %.not = icmp slt i64 %.unbox, %7
  br i1 %.not, label %L16, label %L18

L16:                                              ; preds = %top
  %8 = getelementptr inbounds ptr, ptr %gcframe1, i64 9
  %9 = getelementptr inbounds ptr, ptr %gcframe1, i64 10
  %10 = getelementptr inbounds i8, ptr %"new::#_growend!##0#_growend!##1", i64 8
  store i64 %7, ptr %10, align 8
  %11 = getelementptr inbounds i8, ptr %"new::#_growend!##0#_growend!##1", i64 16
  store i64 %7, ptr %11, align 8
  %12 = getelementptr inbounds i8, ptr %"new::#_growend!##0#_growend!##1", i64 24
  store i64 1, ptr %12, align 8
  %13 = getelementptr inbounds i8, ptr %"new::#_growend!##0#_growend!##1", i64 32
  store i64 0, ptr %13, align 8
  %14 = getelementptr inbounds i8, ptr %"new::#_growend!##0#_growend!##1", i64 40
  store i64 %.unbox, ptr %14, align 8
  %15 = getelementptr inbounds i8, ptr %"new::#_growend!##0#_growend!##1", i64 56
  store ptr %memory_data, ptr %15, align 8
  %16 = getelementptr inbounds i8, ptr %"new::#_growend!##0#_growend!##1", i64 64
  store i64 -1, ptr %16, align 8
  store ptr %"new::Array", ptr %9, align 8
  %17 = getelementptr inbounds ptr, ptr %gcframe1, i64 11
  store ptr @"jl_global#264.jit", ptr %17, align 8
  %18 = getelementptr inbounds ptr, ptr %gcframe1, i64 12
  store ptr @"jl_global#264.jit", ptr %18, align 8
  %gc_slot_addr_12 = getelementptr inbounds ptr, ptr %gcframe1, i64 14
  store ptr %"new::Array", ptr %gc_slot_addr_12, align 8
  call void @"j_#_growend!##0_266"(ptr noalias nocapture noundef nonnull sret({ ptr, ptr }) %sret_box, ptr noalias nocapture noundef nonnull %8, ptr nocapture nonnull readonly %"new::#_growend!##0#_growend!##1", ptr nocapture nonnull readonly %9)
  %memoryref_data.pre = load ptr, ptr %"new::Array", align 8
  %memoryref_mem.pre = load ptr, ptr %4, align 8
  %.pre = ptrtoint ptr %memoryref_data.pre to i64
  br label %L18

L18:                                              ; preds = %L16, %top
  %.pre-phi = phi i64 [ %.pre, %L16 ], [ %6, %top ]
  %19 = phi ptr [ %memoryref_mem.pre, %L16 ], [ @"jl_global#264.jit", %top ]
  %20 = phi ptr [ %memoryref_data.pre, %L16 ], [ %memory_data, %top ]
  store i64 1, ptr %"new::Array.size_ptr", align 8
  store i8 %"x::Int8", ptr %20, align 1
  %21 = add i8 %"x::Int8", 1
  %memory_data_ptr14 = getelementptr inbounds { i64, ptr }, ptr %19, i64 0, i32 1
  %memory_data15 = load ptr, ptr %memory_data_ptr14, align 8
  %22 = ptrtoint ptr %memory_data15 to i64
  %memoryref_offset16 = sub i64 %.pre-phi, %22
  %23 = add i64 %memoryref_offset16, 2
  %.unbox18 = load i64, ptr %19, align 8
  %.not132 = icmp slt i64 %.unbox18, %23
  br i1 %.not132, label %L42, label %L44

L42:                                              ; preds = %L18
  %24 = add i64 %memoryref_offset16, 1
  %25 = getelementptr inbounds i8, ptr %"new::#_growend!##0#_growend!##119", i64 8
  store i64 %23, ptr %25, align 8
  %26 = getelementptr inbounds i8, ptr %"new::#_growend!##0#_growend!##119", i64 16
  store i64 %24, ptr %26, align 8
  %27 = getelementptr inbounds i8, ptr %"new::#_growend!##0#_growend!##119", i64 24
  store i64 2, ptr %27, align 8
  %28 = getelementptr inbounds i8, ptr %"new::#_growend!##0#_growend!##119", i64 32
  store i64 1, ptr %28, align 8
  %29 = getelementptr inbounds i8, ptr %"new::#_growend!##0#_growend!##119", i64 40
  store i64 %.unbox18, ptr %29, align 8
  %30 = getelementptr inbounds i8, ptr %"new::#_growend!##0#_growend!##119", i64 56
  store ptr %20, ptr %30, align 8
  %31 = getelementptr inbounds i8, ptr %"new::#_growend!##0#_growend!##119", i64 64
  store i64 -1, ptr %31, align 8
  store ptr %"new::Array", ptr %2, align 8
  %32 = getelementptr inbounds ptr, ptr %gcframe1, i64 6
  store ptr %19, ptr %32, align 8
  %33 = getelementptr inbounds ptr, ptr %gcframe1, i64 7
  store ptr %19, ptr %33, align 8
  %gc_slot_addr_12156 = getelementptr inbounds ptr, ptr %gcframe1, i64 14
  store ptr %"new::Array", ptr %gc_slot_addr_12156, align 8
  call void @"j_#_growend!##0_266"(ptr noalias nocapture noundef nonnull sret({ ptr, ptr }) %sret_box20, ptr noalias nocapture noundef nonnull %0, ptr nocapture nonnull readonly %"new::#_growend!##0#_growend!##119", ptr nocapture nonnull readonly %2)
  %memoryref_data26.pre = load ptr, ptr %"new::Array", align 8
  %memoryref_mem32.pre = load ptr, ptr %4, align 8
  %.pre150 = ptrtoint ptr %memoryref_data26.pre to i64
  br label %L44

L44:                                              ; preds = %L42, %L18
  %.pre-phi151 = phi i64 [ %.pre150, %L42 ], [ %.pre-phi, %L18 ]
  %.pre-phi149 = phi ptr [ %memoryref_mem32.pre, %L42 ], [ %19, %L18 ]
  %34 = phi ptr [ %memoryref_data26.pre, %L42 ], [ %20, %L18 ]
  store i64 2, ptr %"new::Array.size_ptr", align 8
  %memoryref_data34 = getelementptr i8, ptr %34, i64 1
  store i8 %21, ptr %memoryref_data34, align 1
  %memory_data_ptr38 = getelementptr inbounds { i64, ptr }, ptr %.pre-phi149, i64 0, i32 1
  %memory_data39 = load ptr, ptr %memory_data_ptr38, align 8
  %35 = ptrtoint ptr %memory_data39 to i64
  %memoryref_offset40 = sub i64 %.pre-phi151, %35
  %36 = add i64 %memoryref_offset40, 3
  %.unbox42 = load i64, ptr %.pre-phi149, align 8
  %.not133 = icmp slt i64 %.unbox42, %36
  br i1 %.not133, label %L68, label %L181

L68:                                              ; preds = %L44
  %37 = add i64 %memoryref_offset40, 1
  %38 = getelementptr inbounds i8, ptr %"new::#_growend!##0#_growend!##143", i64 8
  store i64 %36, ptr %38, align 8
  %39 = getelementptr inbounds i8, ptr %"new::#_growend!##0#_growend!##143", i64 16
  store i64 %37, ptr %39, align 8
  %40 = getelementptr inbounds i8, ptr %"new::#_growend!##0#_growend!##143", i64 24
  store i64 3, ptr %40, align 8
  %41 = getelementptr inbounds i8, ptr %"new::#_growend!##0#_growend!##143", i64 32
  store i64 2, ptr %41, align 8
  %42 = getelementptr inbounds i8, ptr %"new::#_growend!##0#_growend!##143", i64 40
  store i64 %.unbox42, ptr %42, align 8
  %43 = getelementptr inbounds i8, ptr %"new::#_growend!##0#_growend!##143", i64 56
  store ptr %34, ptr %43, align 8
  %44 = getelementptr inbounds i8, ptr %"new::#_growend!##0#_growend!##143", i64 64
  store i64 -1, ptr %44, align 8
  store ptr %"new::Array", ptr %3, align 8
  %45 = getelementptr inbounds ptr, ptr %gcframe1, i64 3
  store ptr %.pre-phi149, ptr %45, align 8
  %46 = getelementptr inbounds ptr, ptr %gcframe1, i64 4
  store ptr %.pre-phi149, ptr %46, align 8
  %gc_slot_addr_12157 = getelementptr inbounds ptr, ptr %gcframe1, i64 14
  store ptr %"new::Array", ptr %gc_slot_addr_12157, align 8
  call void @"j_#_growend!##0_266"(ptr noalias nocapture noundef nonnull sret({ ptr, ptr }) %sret_box44, ptr noalias nocapture noundef nonnull %1, ptr nocapture nonnull readonly %"new::#_growend!##0#_growend!##143", ptr nocapture nonnull readonly %3)
  %memoryref_data50.pre = load ptr, ptr %"new::Array", align 8
  %memoryref_data95.phi.trans.insert = getelementptr inbounds i8, ptr %memoryref_data50.pre, i64 1
  %.pre164 = load i8, ptr %memoryref_data95.phi.trans.insert, align 1
  br label %L181

L181:                                             ; preds = %L68, %L44
  %47 = phi i8 [ %.pre164, %L68 ], [ %21, %L44 ]
  %.pre-phi153 = phi ptr [ %memoryref_data50.pre, %L68 ], [ %34, %L44 ]
  %48 = add i8 %"x::Int8", 2
  store i64 3, ptr %"new::Array.size_ptr", align 8
  %memoryref_data58 = getelementptr i8, ptr %.pre-phi153, i64 2
  store i8 %48, ptr %memoryref_data58, align 1
  %49 = load i8, ptr %.pre-phi153, align 1
  %50 = add i8 %47, %49
  %51 = add i8 %48, %50
  %frame.prev163 = load ptr, ptr %frame.prev, align 8
  store ptr %frame.prev163, ptr %tls_pgcstack, align 8
  ret i8 %51
}

; Function Attrs: noinline optnone
define nonnull ptr @jfptr_f_tj1_263(ptr %"function::Core.Function", ptr noalias nocapture noundef readonly %"args::Any[]", i32 %"nargs::UInt32") #1 {
top:
  %0 = getelementptr inbounds i8, ptr %"args::Any[]", i32 0
  %1 = load ptr, ptr %0, align 8
  %.unbox = load i8, ptr %1, align 1
  %2 = call i8 @julia_f_tj1_262(i8 signext %.unbox)
  %3 = zext i8 %2 to i32
  %4 = getelementptr inbounds [256 x ptr], ptr @jl_boxed_int8_cache, i32 0, i32 %3
  %5 = load ptr, ptr %4, align 8
  ret ptr %5
}

; Function Attrs: mustprogress nocallback nofree nosync nounwind speculatable willreturn memory(none)
declare void @llvm.dbg.value(metadata, metadata, metadata) #2

; Function Attrs: mustprogress nounwind willreturn allockind("alloc") allocsize(1) memory(argmem: read, inaccessiblemem: readwrite)
declare noalias nonnull ptr @julia.gc_alloc_obj(ptr, i64, ptr) #3

; Function Signature: (::Base.var"#_growend!##0#_growend!##1"{Array{Int8, 1}, Int64, Int64, Int64, Int64, Int64, Memory{Int8}, GenericMemoryRef{:not_atomic, Int8, Core.AddrSpace{Core}(0x00)}})()
declare void @"j_#_growend!##0_266"(ptr noalias nocapture noundef sret({ ptr, ptr }), ptr noalias nocapture noundef, ptr nocapture readonly, ptr nocapture readonly) #4

; Function Attrs: mustprogress nocallback nofree nounwind willreturn memory(argmem: write)
declare void @llvm.memset.p0.i64(ptr nocapture writeonly, i8, i64, i1 immarg) #5

; Function Attrs: mustprogress nofree norecurse nosync nounwind speculatable willreturn memory(none)
declare noundef nonnull ptr @julia.gc_loaded(ptr nocapture noundef nonnull readnone, ptr noundef nonnull readnone) #6

; Function Signature: mapreduce_impl(typeof(Base.identity), typeof(Base.:(+)), Array{Int8, 1}, Int64, Int64, Int64)
declare i8 @j_mapreduce_impl_268(ptr, i64 signext, i64 signext, i64 signext) #7

; Function Attrs: nocallback nofree nosync nounwind willreturn memory(argmem: readwrite)
declare void @llvm.lifetime.start.p0(i64 immarg, ptr nocapture) #8

; Function Attrs: nocallback nofree nosync nounwind willreturn memory(argmem: readwrite)
declare void @llvm.lifetime.end.p0(i64 immarg, ptr nocapture) #8

; Function Attrs: nounwind willreturn allockind("alloc") allocsize(2) memory(argmem: read, inaccessiblemem: readwrite)
declare noalias nonnull ptr @ijl_gc_small_alloc(ptr, i32, i32, i64) #9

declare noalias nonnull ptr @julia.new_gc_frame(i32)

declare void @julia.push_gc_frame(ptr, i32)

declare ptr @julia.get_gc_frame_slot(ptr, i32)

declare void @julia.pop_gc_frame(ptr)

; Function Attrs: nounwind willreturn allockind("alloc") allocsize(1) memory(argmem: read, inaccessiblemem: readwrite)
declare noalias nonnull ptr @julia.gc_alloc_bytes(ptr, i64, i64) #10

; Function Attrs: memory(argmem: readwrite, inaccessiblemem: readwrite)
declare void @ijl_gc_queue_root(ptr) #11

; Function Attrs: nounwind willreturn allockind("alloc") allocsize(1) memory(argmem: read, inaccessiblemem: readwrite)
declare noalias nonnull ptr @ijl_gc_big_alloc(ptr, i64, i64) #10

; Function Attrs: nounwind willreturn allockind("alloc") allocsize(1) memory(argmem: read, inaccessiblemem: readwrite)
declare noalias nonnull ptr @ijl_gc_alloc_typed(ptr, i64, i64) #10

attributes #0 = { "frame-pointer"="all" "julia.fsig"="f_tj1(Int8)" "probe-stack"="inline-asm" }
attributes #1 = { noinline optnone "frame-pointer"="all" "probe-stack"="inline-asm" }
attributes #2 = { mustprogress nocallback nofree nosync nounwind speculatable willreturn memory(none) }
attributes #3 = { mustprogress nounwind willreturn allockind("alloc") allocsize(1) memory(argmem: read, inaccessiblemem: readwrite) }
attributes #4 = { "frame-pointer"="all" "julia.fsig"="(::Base.var\22#_growend!##0#_growend!##1\22{Array{Int8, 1}, Int64, Int64, Int64, Int64, Int64, Memory{Int8}, GenericMemoryRef{:not_atomic, Int8, Core.AddrSpace{Core}(0x00)}})()" "probe-stack"="inline-asm" }
attributes #5 = { mustprogress nocallback nofree nounwind willreturn memory(argmem: write) }
attributes #6 = { mustprogress nofree norecurse nosync nounwind speculatable willreturn memory(none) }
attributes #7 = { "frame-pointer"="all" "julia.fsig"="mapreduce_impl(typeof(Base.identity), typeof(Base.:(+)), Array{Int8, 1}, Int64, Int64, Int64)" "probe-stack"="inline-asm" }
attributes #8 = { nocallback nofree nosync nounwind willreturn memory(argmem: readwrite) }
attributes #9 = { nounwind willreturn allockind("alloc") allocsize(2) memory(argmem: read, inaccessiblemem: readwrite) }
attributes #10 = { nounwind willreturn allockind("alloc") allocsize(1) memory(argmem: read, inaccessiblemem: readwrite) }
attributes #11 = { memory(argmem: readwrite, inaccessiblemem: readwrite) }
attributes #12 = { nounwind }

!llvm.module.flags = !{!0, !1}

!0 = !{i32 2, !"Dwarf Version", i32 4}
!1 = !{i32 2, !"Debug Info Version", i32 3}
