; AUTO-GENERATED by scripts/gen_heap_fixtures.jl (Bennett-2mj3).
; Source: heap_m1_f1.ll — captured from `code_llvm(...; optimize=true,
;   dump_module=true)` under DEFAULT check-bounds. Regenerate with
;   `julia --project scripts/gen_heap_fixtures.jl` (NOT --check-bounds=yes).
; ModuleID = 'f1'
source_filename = "f1"
target datalayout = "e-m:e-p270:32:32-p271:32:32-p272:64:64-i64:64-i128:128-f80:128-n8:16:32:64-S128"
target triple = "x86_64-unknown-linux-gnu"

@jl_boxed_int8_cache = external constant [256 x ptr]
@"_j_const#2" = private unnamed_addr constant i64 1, align 8

@"+Core.Array#231.jit" = private alias ptr, inttoptr (i64 139761035024784 to ptr)
@"jl_global#230.jit" = private alias ptr, inttoptr (i64 139761038565856 to ptr)

; Function Signature: f1(Int8)
define i8 @julia_f1_228(i8 signext %"x::Int8") #0 {
top:
  %gcframe1 = alloca [7 x ptr], align 16
  call void @llvm.memset.p0.i64(ptr align 16 %gcframe1, i8 0, i64 56, i1 true)
  %"new::#_growend!##0#_growend!##1" = alloca [9 x i64], align 8
  %sret_box = alloca [2 x i64], align 8
  %thread_ptr = call ptr asm "movq %fs:0, $0", "=r"() #12
  %tls_ppgcstack = getelementptr inbounds i8, ptr %thread_ptr, i64 -8
  %tls_pgcstack = load ptr, ptr %tls_ppgcstack, align 8
  store i64 20, ptr %gcframe1, align 8
  %frame.prev = getelementptr inbounds ptr, ptr %gcframe1, i64 1
  %task.gcstack = load ptr, ptr %tls_pgcstack, align 8
  store ptr %task.gcstack, ptr %frame.prev, align 8
  store ptr %gcframe1, ptr %tls_pgcstack, align 8
  %memory_data = load ptr, ptr getelementptr inbounds (ptr, ptr @"jl_global#230.jit", i64 1), align 8
  %ptls_field = getelementptr inbounds i8, ptr %tls_pgcstack, i64 16
  %ptls_load = load ptr, ptr %ptls_field, align 8
  %"new::Array" = call noalias nonnull align 8 dereferenceable(32) ptr @ijl_gc_small_alloc(ptr %ptls_load, i32 408, i32 32, i64 139761035024784) #9
  %"new::Array.tag_addr" = getelementptr inbounds i64, ptr %"new::Array", i64 -1
  store atomic i64 139761035024784, ptr %"new::Array.tag_addr" unordered, align 8
  %0 = getelementptr inbounds i8, ptr %"new::Array", i64 8
  store ptr %memory_data, ptr %"new::Array", align 8
  store ptr @"jl_global#230.jit", ptr %0, align 8
  %"new::Array.size_ptr" = getelementptr inbounds i8, ptr %"new::Array", i64 16
  store i64 0, ptr %"new::Array.size_ptr", align 8
  %memory_data3 = load ptr, ptr getelementptr inbounds (ptr, ptr @"jl_global#230.jit", i64 1), align 8
  %1 = ptrtoint ptr %memory_data3 to i64
  %2 = ptrtoint ptr %memory_data to i64
  %memoryref_offset = sub i64 %2, %1
  %3 = add i64 %memoryref_offset, 1
  %.unbox = load i64, ptr @"jl_global#230.jit", align 8
  %.not = icmp slt i64 %.unbox, %3
  br i1 %.not, label %L16, label %L43

L16:                                              ; preds = %top
  %4 = getelementptr inbounds ptr, ptr %gcframe1, i64 2
  %5 = getelementptr inbounds ptr, ptr %gcframe1, i64 3
  %6 = getelementptr inbounds i8, ptr %"new::#_growend!##0#_growend!##1", i64 8
  store i64 %3, ptr %6, align 8
  %7 = getelementptr inbounds i8, ptr %"new::#_growend!##0#_growend!##1", i64 16
  store i64 %3, ptr %7, align 8
  %8 = getelementptr inbounds i8, ptr %"new::#_growend!##0#_growend!##1", i64 24
  store i64 1, ptr %8, align 8
  %9 = getelementptr inbounds i8, ptr %"new::#_growend!##0#_growend!##1", i64 32
  store i64 0, ptr %9, align 8
  %10 = getelementptr inbounds i8, ptr %"new::#_growend!##0#_growend!##1", i64 40
  store i64 %.unbox, ptr %10, align 8
  %11 = getelementptr inbounds i8, ptr %"new::#_growend!##0#_growend!##1", i64 56
  store ptr %memory_data, ptr %11, align 8
  %12 = getelementptr inbounds i8, ptr %"new::#_growend!##0#_growend!##1", i64 64
  store i64 -1, ptr %12, align 8
  store ptr %"new::Array", ptr %5, align 8
  %13 = getelementptr inbounds ptr, ptr %gcframe1, i64 4
  store ptr @"jl_global#230.jit", ptr %13, align 8
  %14 = getelementptr inbounds ptr, ptr %gcframe1, i64 5
  store ptr @"jl_global#230.jit", ptr %14, align 8
  %gc_slot_addr_4 = getelementptr inbounds ptr, ptr %gcframe1, i64 6
  store ptr %"new::Array", ptr %gc_slot_addr_4, align 8
  call void @"j_#_growend!##0_232"(ptr noalias nocapture noundef nonnull sret({ ptr, ptr }) %sret_box, ptr noalias nocapture noundef nonnull %4, ptr nocapture nonnull readonly %"new::#_growend!##0#_growend!##1", ptr nocapture nonnull readonly %5)
  %memoryref_data.pre = load ptr, ptr %"new::Array", align 8
  br label %L43

L43:                                              ; preds = %L16, %top
  %memoryref_data14 = phi ptr [ %memoryref_data.pre, %L16 ], [ %memory_data, %top ]
  store i64 1, ptr %"new::Array.size_ptr", align 8
  store i8 %"x::Int8", ptr %memoryref_data14, align 1
  %frame.prev31 = load ptr, ptr %frame.prev, align 8
  store ptr %frame.prev31, ptr %tls_pgcstack, align 8
  ret i8 %"x::Int8"
}

; Function Attrs: noinline optnone
define nonnull ptr @jfptr_f1_229(ptr %"function::Core.Function", ptr noalias nocapture noundef readonly %"args::Any[]", i32 %"nargs::UInt32") #1 {
top:
  %0 = getelementptr inbounds i8, ptr %"args::Any[]", i32 0
  %1 = load ptr, ptr %0, align 8
  %.unbox = load i8, ptr %1, align 1
  %2 = call i8 @julia_f1_228(i8 signext %.unbox)
  %3 = zext i8 %2 to i32
  %4 = getelementptr inbounds [256 x ptr], ptr @jl_boxed_int8_cache, i32 0, i32 %3
  %5 = load ptr, ptr %4, align 8
  ret ptr %5
}

; Function Attrs: mustprogress nocallback nofree nosync nounwind speculatable willreturn memory(none)
declare void @llvm.dbg.value(metadata, metadata, metadata) #2

; Function Attrs: mustprogress nounwind willreturn allockind("alloc") allocsize(1) memory(argmem: read, inaccessiblemem: readwrite)
declare noalias nonnull ptr @julia.gc_alloc_obj(ptr, i64, ptr) #3

; Function Signature: (::Base.var"#_growend!##0#_growend!##1"{Array{Int8, 1}, Int64, Int64, Int64, Int64, Int64, Memory{Int8}, GenericMemoryRef{:not_atomic, Int8, Core.AddrSpace{Core}(0x00)}})()
declare void @"j_#_growend!##0_232"(ptr noalias nocapture noundef sret({ ptr, ptr }), ptr noalias nocapture noundef, ptr nocapture readonly, ptr nocapture readonly) #4

; Function Attrs: mustprogress nocallback nofree nounwind willreturn memory(argmem: write)
declare void @llvm.memset.p0.i64(ptr nocapture writeonly, i8, i64, i1 immarg) #5

; Function Attrs: mustprogress nofree norecurse nosync nounwind speculatable willreturn memory(none)
declare noundef nonnull ptr @julia.gc_loaded(ptr nocapture noundef nonnull readnone, ptr noundef nonnull readnone) #6

; Function Signature: throw_boundserror(Array{Int8, 1}, Tuple{Int64})
; Function Attrs: noreturn
declare void @j_throw_boundserror_233(ptr, ptr nocapture readonly) #7

; Function Attrs: nocallback nofree nosync nounwind willreturn memory(argmem: readwrite)
declare void @llvm.lifetime.start.p0(i64 immarg, ptr nocapture) #8

; Function Attrs: nocallback nofree nosync nounwind willreturn memory(argmem: readwrite)
declare void @llvm.lifetime.end.p0(i64 immarg, ptr nocapture) #8

; Function Attrs: nounwind willreturn allockind("alloc") allocsize(2) memory(argmem: read, inaccessiblemem: readwrite)
declare noalias nonnull ptr @ijl_gc_small_alloc(ptr, i32, i32, i64) #9

declare noalias nonnull ptr @julia.new_gc_frame(i32)

declare void @julia.push_gc_frame(ptr, i32)

declare ptr @julia.get_gc_frame_slot(ptr, i32)

declare void @julia.pop_gc_frame(ptr)

; Function Attrs: nounwind willreturn allockind("alloc") allocsize(1) memory(argmem: read, inaccessiblemem: readwrite)
declare noalias nonnull ptr @julia.gc_alloc_bytes(ptr, i64, i64) #10

; Function Attrs: memory(argmem: readwrite, inaccessiblemem: readwrite)
declare void @ijl_gc_queue_root(ptr) #11

; Function Attrs: nounwind willreturn allockind("alloc") allocsize(1) memory(argmem: read, inaccessiblemem: readwrite)
declare noalias nonnull ptr @ijl_gc_big_alloc(ptr, i64, i64) #10

; Function Attrs: nounwind willreturn allockind("alloc") allocsize(1) memory(argmem: read, inaccessiblemem: readwrite)
declare noalias nonnull ptr @ijl_gc_alloc_typed(ptr, i64, i64) #10

attributes #0 = { "frame-pointer"="all" "julia.fsig"="f1(Int8)" "probe-stack"="inline-asm" }
attributes #1 = { noinline optnone "frame-pointer"="all" "probe-stack"="inline-asm" }
attributes #2 = { mustprogress nocallback nofree nosync nounwind speculatable willreturn memory(none) }
attributes #3 = { mustprogress nounwind willreturn allockind("alloc") allocsize(1) memory(argmem: read, inaccessiblemem: readwrite) }
attributes #4 = { "frame-pointer"="all" "julia.fsig"="(::Base.var\22#_growend!##0#_growend!##1\22{Array{Int8, 1}, Int64, Int64, Int64, Int64, Int64, Memory{Int8}, GenericMemoryRef{:not_atomic, Int8, Core.AddrSpace{Core}(0x00)}})()" "probe-stack"="inline-asm" }
attributes #5 = { mustprogress nocallback nofree nounwind willreturn memory(argmem: write) }
attributes #6 = { mustprogress nofree norecurse nosync nounwind speculatable willreturn memory(none) }
attributes #7 = { noreturn "frame-pointer"="all" "julia.fsig"="throw_boundserror(Array{Int8, 1}, Tuple{Int64})" "probe-stack"="inline-asm" }
attributes #8 = { nocallback nofree nosync nounwind willreturn memory(argmem: readwrite) }
attributes #9 = { nounwind willreturn allockind("alloc") allocsize(2) memory(argmem: read, inaccessiblemem: readwrite) }
attributes #10 = { nounwind willreturn allockind("alloc") allocsize(1) memory(argmem: read, inaccessiblemem: readwrite) }
attributes #11 = { memory(argmem: readwrite, inaccessiblemem: readwrite) }
attributes #12 = { nounwind }

!llvm.module.flags = !{!0, !1}

!0 = !{i32 2, !"Dwarf Version", i32 4}
!1 = !{i32 2, !"Debug Info Version", i32 3}
