# Documenter.jl wiring for Bennett.jl. Builds the Diátaxis-structured site
# under docs/src/ (getting_started / tutorials / howto / explanation / reference)
# plus an autogenerated reference/autodocs.md that pulls public-API docstrings
# via @docs blocks. Local-only — no deploydocs, no GitHub CI per CLAUDE.md §14.
#
# Build:
#   julia --project=docs -e 'using Pkg; Pkg.develop(path="."); Pkg.instantiate()'
#   julia --project=docs docs/make.jl
#   # -> open docs/build/index.html
#
# doctest is currently disabled: the prose pages show live-verified outputs as
# plain ```julia blocks rather than executed ```jldoctest fences. To restore the
# docstring-doctest regression surface, set doctest=true and validate the build.

using Documenter
using Bennett

DocMeta.setdocmeta!(Bennett, :DocTestSetup, :(using Bennett); recursive=true)

makedocs(
    sitename = "Bennett.jl",
    modules = [Bennett],
    authors = "Tobias Osborne",
    pages = [
        "Home" => "index.md",
        "Getting started" => [
            "Installation" => "getting_started/install.md",
            "Quick start" => "getting_started/quickstart.md",
        ],
        "Tutorials" => [
            "Your first circuit" => "tutorials/first_circuit.md",
            "Reading the gates" => "tutorials/reading_the_gates.md",
            "Control flow & loops" => "tutorials/control_flow_and_loops.md",
            "Floats & transcendentals" => "tutorials/floats.md",
        ],
        "How-to guides" => [
            "Choose an arithmetic strategy" => "howto/arithmetic_strategy.md",
            "Reversible memory" => "howto/reversible_memory.md",
            "Compile C / Rust" => "howto/other_languages.md",
            "Target the reversible VM" => "howto/reversible_vm.md",
            "Quantum control" => "howto/quantum_control.md",
        ],
        "Explanation" => [
            "Architecture" => "explanation/architecture.md",
            "Bennett's construction" => "explanation/bennett_construction.md",
            "Why branchless soft-float" => "explanation/branchless_softfloat.md",
            "Architectural limits" => "explanation/architectural_limits.md",
        ],
        "Reference" => [
            "API" => "reference/api.md",
            "Strategies" => "reference/strategies.md",
            "Bibliography" => "reference/bibliography.md",
            "Docstrings (autogen)" => "reference/autodocs.md",
        ],
    ],
    doctest = false,
    checkdocs = :none,
    warnonly = [:missing_docs, :cross_references, :docs_block],
    format = Documenter.HTML(prettyurls = false),
)
